# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  phpVersion: 7.4

steps:
- script: |
      sudo add-apt-repository ppa:ondrej/php
      sudo apt-get update
      sudo apt-get install -y php7.4
      sudo update-alternatives --set php /usr/bin/php7.4
      sudo update-alternatives --set phar /usr/bin/phar7.4
      sudo update-alternatives --set phpdbg /usr/bin/phpdbg7.4
      sudo update-alternatives --set php-cgi /usr/bin/php-cgi7.4
      sudo update-alternatives --set phar.phar /usr/bin/phar.phar7.4
      php -v
  displayName: 'Use PHP version $(phpVersion)'

- script: composer install --no-interaction --prefer-dist
  displayName: 'composer install'

- script: 
      # Ejecuta las pruebas de PHPUnit
      php artisan test
  displayName: 'Ejecutar pruebas PHPUnit'
