trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      # Usar la imagen de PHP 7.4 de manera explícita
      docker pull php:7.4-fpm

      # Agregar las extensiones necesarias a través de pecl o apt-get
      apt-get update
      apt-get install -y php7.4-fpm php7.4-mbstring php7.4-xmlrpc php7.4-soap php7.4-gd php7.4-xml php7.4-cli php7.4-zip php7.4-bcmath php7.4-tokenizer php7.4-json php-pear
   
      # Reiniciar el servicio de PHP-FPM para aplicar los cambios (ajusta el comando según tu sistema)
      service php7.4-fpm restart
    displayName: 'Configurar extensiones de PHP'

  - script: |
      composer install --no-interaction --prefer-dist
      php artisan test
    displayName: 'Ejecutar pruebas PHPUnit'