# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  phpVersion: 7.4

steps:
- script: |
      sudo add-apt-repository ppa:ondrej/php
      sudo apt-get update
      sudo apt-get install -y php7.4 libapache2-mod-php7.4 php7.4-mbstring php7.4-xmlrpc php7.4-soap php7.4-gd php7.4-xml php7.4-cli php7.4-zip php7.4-bcmath php7.4-tokenizer php7.4-json php7.4-pear
      sudo update-alternatives --set php /usr/bin/php7.4
      sudo update-alternatives --set phar /usr/bin/phar7.4
      sudo update-alternatives --set phpdbg /usr/bin/phpdbg7.4
      sudo update-alternatives --set php-cgi /usr/bin/php-cgi7.4
      sudo update-alternatives --set phar.phar /usr/bin/phar.phar7.4
      php -v
  displayName: 'Configurar PHP 7.4 y extensiones'

- script: composer install --no-interaction --prefer-dist
  displayName: 'composer install'

- script: 
      # Ejecuta las pruebas de PHPUnit
      php artisan test
  displayName: 'Ejecutar pruebas PHPUnit'
