trigger:
- main

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'subscription-id'
  # Web app name
  webAppName: 'web-app-name'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  # Environment name
  environmentName: 'environment-name'
  # Root folder under which your composer.json file is available.
  rootFolder: $(System.DefaultWorkingDirectory)

stages:
- stage: Build
  displayName: Build stage
  variables:
    phpVersion: '7.4'
  jobs:
  - job: BuildJob
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: |
        sudo apt-get update
        sudo apt -y install software-properties-common
        sudo add-apt-repository ppa:ondrej/php
        sudo apt-get update        
        sudo apt -y install php7.4 
        sudo apt-get install php-xml -y
        sudo apt-get install -y php-mbstring
        sudo apt-get install -y php7.4 libapache2-mod-php7.4 php7.4-mbstring php7.4-xmlrpc php7.4-soap php7.4-gd php7.4-xml php7.4-cli php7.4-zip php7.4-bcmath php7.4-tokenizer php7.4-json php7.4-pear   
        sudo apt-get install -y php7.4-dom
        sudo apt-get install -y php7.4-mbstring
        sudo apt-get install php7.4-sqlite3 -y
        sudo update-alternatives --set php /usr/bin/php$(phpVersion)
        sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
        sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
        sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
        sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
        php -version
      workingDirectory: $(rootFolder)
      displayName: 'Use PHP version $(phpVersion)'
    - script: |
        composer install --no-interaction --prefer-dist --ignore-platform-reqs        
      displayName: 'Instalar paquetes de composer'
    - script: |
        php -version   
        php -m 
        cp .env.example .env && php artisan key:generate
        sudo touch database/database.sqlite        
        php artisan config:cache
        unzip json.zip -d storage/app/ 
        sudo chmod 777 database/database.sqlite
        sudo chmod 777 storage/ -R
        sudo chmod 777 vendor/ -R
      displayName: 'Configuración de Laravel'  
    - script: | 
        php artisan migrate:fresh --seed
        php artisan test
        tail -500 storage/logs/laravel.log
      displayName: 'Pruebas de caja blanca'  

  #    - script: |
  #         screen -d -m google-chrome-stable --headless --disable-gpu --disable-dev-shm-usage --disable-software-rasterizer --remote-debugging-port=9222 http://localhost &
  #        screen -d -m php artisan serve &
  #      displayName: 'Starting Chrome and the Web Server'
  #
  #   - script: vendor/bin/phpunit --testdox --verbose
  #     displayName: 'Running Unit Test'
  #
  #  - script: |
  #       php artisan dusk:update 74
  #       php artisan dusk  
    