# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- main

pool:
  vmImage: php:7.4-fpm

variables:
  phpVersion: 7.4

steps:
- script: |
      - apt-get update
      - apt-get install -y unzip libzip-dev libpng-dev zip git
      - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - docker-php-ext-configure zip
      - docker-php-ext-install zip bcmath pcntl gd
      - php -r "file_exists('.env') || copy('.env.example', '.env');"
      - composer install --no-progress --no-suggest --prefer-dist --no-interaction
      - vendor/bin/phpcs --standard=PSR2 -n app
      - apt-get update && apt-get install -y curl gnupg gnupg2 && curl -sL https://deb.nodesource.com/setup_10.x | bash - && apt-get install -y nodejs
      - php artisan key:generate
      - npm install
      - npm run dev
      - php artisan test --parallel
      - vendor/bin/phpstan analyse --memory-limit=512M
