<?php

/** @var \Illuminate\Database\Eloquent\Factory $factory */

use App\Models\Oferta;
use Faker\Generator as Faker;
use Illuminate\Support\Str;

$jobTitles = [
    "Desarrollador de software",
    "Ingeniero de software",
    "Diseñador gráfico",
    "Analista de datos",
    "Especialista en marketing digital",
    "Gerente de proyectos",
    "Administrador de sistemas",
    "Especialista en recursos humanos",
    "Economista",
    "Traductor",
    "Contador",
    "Arquitecto",
    "Enfermero/a",
    "Médico",
    "Ingeniero civil",
    "Abogado",
    "Chef",
    "Diseñador de interiores",
    "Analista financiero",
    "Gerente de ventas",
    "Ingeniero eléctrico",
    "Diseñador de UX/UI",
    "Desarrollador web",
    "Especialista en SEO",
    "Ingeniero mecánico",
    "Director de marketing",
    "Director de recursos humanos",
    "Diseñador de moda",
    "Periodista",
    "Psicólogo",
    "Profesor/a de educación primaria",
    "Profesor/a de secundaria",
    "Técnico de soporte IT",
    "Analista de sistemas",
    "Técnico en radiología",
    "Ingeniero industrial",
    "Analista de seguridad informática",
    "Diseñador industrial",
    "Gerente de operaciones",
    "Gerente de recursos humanos",
    "Director de finanzas",
    "Científico de datos",
    "Especialista en ventas",
    "Ingeniero de calidad",
    "Técnico en redes",
    "Especialista en relaciones públicas",
    "Desarrollador móvil",
    "Diseñador de juegos",
    "Especialista en SEM",
    "Ingeniero de automatización",
    "Ingeniero de producción",
    "Analista de negocios",
    "Ingeniero de sistemas",
    "Diseñador de productos",
    "Asistente administrativo",
    "Asistente de recursos humanos",
    "Contador público",
    "Ingeniero de telecomunicaciones",
    "Asesor financiero",
    "Ingeniero de software embebido",
    "Mecánico automotriz",
    "Especialista en marketing de contenidos",
    "Farmacéutico",
    "Ingeniero de seguridad",
    "Desarrollador de front-end",
    "Diseñador de UI",
    "Analista de marketing",
    "Técnico en electrónica",
    "Ingeniero de diseño",
    "Director de ventas",
    "Desarrollador de back-end",
    "Analista de procesos",
    "Ingeniero de mantenimiento",
    "Especialista en reclutamiento",
    "Especialista en trade marketing",
    "Diseñador de animación",
    "Analista de calidad",
    "Gerente de operaciones de TI",
    "Especialista en logística",
    "Ingeniero de proyectos",
    "Ingeniero de validación",
    "Diseñador de sonido",
    "Especialista en e-commerce",
    "Especialista en seguridad de la información",
    "Analista de recursos humanos",
    "Director creativo",
    "Ingeniero de pruebas",
    "Arquitecto de soluciones",
    "Especialista en email marketing",
    "Técnico en electromecánica",
    "Gerente de producto",
    "Ingeniero de soporte",
    "Técnico en sistemas de automatización",
    "Gerente de relaciones públicas",
    "Analista de riesgos",
    "Desarrollador de videojuegos",
    "Especialista en compensaciones y beneficios",
    "Ingeniero de validación",
    "Diseñador de empaques",
    "Ingeniero de procesos",
    "Gerente de logística",
    "Especialista en relaciones laborales",
    "Asesor legal",
];




$factory->define(Oferta::class, function (Faker $faker)use($jobTitles) {
    
    return [
        'titulo'        => $faker->randomElement($jobTitles),
        'sueldo'        => $faker->biasedNumberBetween(1000000, 5000000),
        'ciudad_id'     => App\Models\Ciudades::all()->random()->id,
        'area_id'       => App\Models\Area::all()->random()->id,
        'user_id'       => App\User::where('tipo_user', 2)->get()->random()->id,
        'vacantes'      => $faker->numberBetween(1, 10),
        'descripcion'   => '<div><b>' . $faker->sentence(3) . '</b>' . $faker->sentence(5) .  '</div><div>' . $faker->text(250) . '</div>',
        'experiencia'   => $faker->randomNumber(2, false),
        'contrato'      => $faker->numberBetween(1, 4),
        'estado'        => 1,
        'uuid'          => Str::uuid(),
    ];
});
